python: 
 - "2.7"
 - "2.6"
services:
 - postgresql
env: 
  secure: tCHXmou2NZSjMMyDs6VOKZn9DPwCsOdHhMI0uspEmKvx4vZmOUTLTlNpdysD9RROsvT/pKJ5Ff5SA4QUel3NHdUuWm5kVDMvFKnsYGVACW1UcGHz1+QBcddXTCjdMjg0n5Ue6lRtQi/L/JtEhnfHJ/LueMEso3Y2PLslymauCl4=
language: python
notifications: 
  hipchat: 
    rooms: 
      secure: J/txhSEXTRRibmPxGQ4YtePQ5aarnCAJhHZP+NP9luW/CyhMD45Aq8PKRNgaCq8kZuVs001HePz4IPceqfJiMjts2Dv1SrJqvpPhl4xxIj8aJgH7b1vlKcSUeum3G8+7ZJrURoIxET5EZL0hDAE7ZFPogaksK0zXKlRQsuATkM0=
before_install: 
 - sudo apt-get install software-properties-common
 - sudo add-apt-repository ppa:gijzelaar/aartfaac
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcasacore-dev casacore-data scons python-numpy-dev python-dev libboost-python-dev python-setuptools subversion libblas-dev liblapack-dev gfortran wcslib-dev libcfitsio3-dev git cmake build-essential python-pip python-numpy python-scipy python-pygresql
 - psql -c 'create database trap;' -U postgres
 - cd /tmp
 - svn checkout http://pyrap.googlecode.com/svn/trunk/ pyrap
 - cd pyrap
 - ./batchbuild-trunk.py  --casacore-root=/usr
 - cd tests
 - svn co --pasword $SVNPASS http://svn.transientskp.org/data/unittests/tkp_lib/ data
install: 
 - pip install -r requirements.txt --use-mirrors
 - mkdir build && cd build
 - cmake ..
 - make
 - make install
script: 
 - nosetests
